function slugifyOperatorName(name) {
    return name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ø/gi, "o").toLowerCase().replace(/[^a-z0-9]/g, "");
}

const RAW_OPERATORS = [ {
    name: "Ash",
    gender: "Female",
    role: "Breach",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2015,
    primaryWeapons: [ "G36C", "R4-C" ],
    secondaryWeapons: [ "5.7 USG", "GONNE-6" ],
    secondaryGadgets: [ "Breach Charge", "Claymore" ]
}, {
    name: "Bandit",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Defense",
    speed: 3,
    armor: 1,
    releaseYear: 2015,
    primaryWeapons: [ "MP7", "M590A1" ],
    secondaryWeapons: [ "P12", "Super Shorty" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Blitz",
    gender: "Male",
    role: "Front Line",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Castle",
    gender: "Male",
    role: "Anti-Entry",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [ "UMP45", "M1014" ],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Barbed Wire", "Nitro Cell" ]
}, {
    name: "Doc",
    gender: "Male",
    role: "Support",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2015,
    primaryWeapons: [ "MP5", "P90" ],
    secondaryWeapons: [ "P9" ],
    secondaryGadgets: [ "Bulletproof Camera", "Barbed Wire" ]
}, {
    name: "Fuze",
    gender: "Male",
    role: "Front Line",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2015,
    primaryWeapons: [ "AK-12", "6P41" ],
    secondaryWeapons: [ "GSH-18", "Bearing 9" ],
    secondaryGadgets: [ "Frag Grenade", "Breach Charge" ]
}, {
    name: "Glaz",
    gender: "Male",
    role: "Support",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2015,
    primaryWeapons: [ "OTs-03" ],
    secondaryWeapons: [ "GSH-18", "PMM" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "IQ",
    gender: "Female",
    role: "Intel",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2015,
    primaryWeapons: [ "552 Commando", "AUG A2" ],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Frag Grenade", "Breach Charge" ]
}, {
    name: "Jäger",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [ "416-C Carbine", "M870" ],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Kapkan",
    gender: "Male",
    role: "Trapper",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [ "9x19VSN", "SASG-12" ],
    secondaryWeapons: [ "PMM", "GSH-18" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Montagne",
    gender: "Male",
    role: "Front Line",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2015,
    primaryWeapons: [],
    secondaryWeapons: [ "P9" ],
    secondaryGadgets: [ "Smoke Grenade", "Breach Charge" ]
}, {
    name: "Mute",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2015,
    primaryWeapons: [ "MP5K", "M590A1" ],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Barbed Wire", "Nitro Cell" ]
}, {
    name: "Pulse",
    gender: "Male",
    role: "Intel",
    side: "Defense",
    speed: 3,
    armor: 1,
    releaseYear: 2015,
    primaryWeapons: [ "UMP45", "M1014" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Rook",
    gender: "Male",
    role: "Support",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2015,
    primaryWeapons: [ "MP5", "M590A1" ],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Sledge",
    gender: "Male",
    role: "Breach",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [ "L85A2", "M590A1" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Smoke",
    gender: "Male",
    role: "Anti-Entry",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [ "FMG-9", "M590A1" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Barbed Wire", "Deployable Shield" ]
}, {
    name: "Tachanka",
    gender: "Male",
    role: "Crowd Control",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2015,
    primaryWeapons: [ "6P41", "DP27" ],
    secondaryWeapons: [ "PMM", "GSH-18" ],
    secondaryGadgets: [ "Proximity Alarm", "Impact Grenade" ]
}, {
    name: "Thatcher",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2015,
    primaryWeapons: [ "L85A2", "AR33" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Flash Grenade", "Smoke Grenade" ]
}, {
    name: "Thermite",
    gender: "Male",
    role: "Breach",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [ "556XI", "M1014" ],
    secondaryWeapons: [ "5.7 USG" ],
    secondaryGadgets: [ "Smoke Grenade", "Breach Charge" ]
}, {
    name: "Twitch",
    gender: "Female",
    role: "Anti-Gadget",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2015,
    primaryWeapons: [ "F2", "417" ],
    secondaryWeapons: [ "5.7 USG" ],
    secondaryGadgets: [ "Smoke Grenade", "Hard Breach Charge" ]
}, {
    name: "Buck",
    gender: "Male",
    role: "Breach",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2016,
    primaryWeapons: [ "C8-SFW", "CAMRS" ],
    secondaryWeapons: [ "MK1 9mm" ],
    secondaryGadgets: [ "Frag Grenade", "Stun Grenade" ]
}, {
    name: "Frost",
    gender: "Female",
    role: "Trapper",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2016,
    primaryWeapons: [ "9mm C1", "SuperNova" ],
    secondaryWeapons: [ "Super Shorty", "P9" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Blackbeard",
    gender: "Male",
    role: "Front Line",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2016,
    primaryWeapons: [ "SR-25", "M590A1" ],
    secondaryWeapons: [ "1911 TACOPS" ],
    secondaryGadgets: [ "Frag Grenade", "Claymore" ]
}, {
    name: "Valkyrie",
    gender: "Female",
    role: "Intel",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2016,
    primaryWeapons: [ "MP5SD", "SPAS-12" ],
    secondaryWeapons: [ "D-50", "5.7 USG" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Capitão",
    gender: "Male",
    role: "Front Line",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2016,
    primaryWeapons: [ "PARA-308", "M249" ],
    secondaryWeapons: [ "PRB92" ],
    secondaryGadgets: [ "Smoke Grenade", "Claymore" ]
}, {
    name: "Caveira",
    gender: "Female",
    role: "Intel",
    side: "Defense",
    speed: 3,
    armor: 1,
    releaseYear: 2016,
    primaryWeapons: [ "M12", "SPAS-15" ],
    secondaryWeapons: [ "Luison" ],
    secondaryGadgets: [ "Proximity Alarm", "Impact Grenade" ]
}, {
    name: "Echo",
    gender: "Male",
    role: "Intel",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2016,
    primaryWeapons: [ "MP5", "M590A1" ],
    secondaryWeapons: [ "FN Five-seveN" ],
    secondaryGadgets: [ "Barbed Wire", "Nitro Cell" ]
}, {
    name: "Hibana",
    gender: "Female",
    role: "Breach",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2016,
    primaryWeapons: [ "Type-89", "SUPERNOVA" ],
    secondaryWeapons: [ "P229" ],
    secondaryGadgets: [ "Stun Grenade", "Breach Charge" ]
}, {
    name: "Jackal",
    gender: "Male",
    role: "Intel",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2017,
    primaryWeapons: [ "C7E", "PDW9" ],
    secondaryWeapons: [ "ITA12L", "USP40" ],
    secondaryGadgets: [ "Hard Breach Charge", "Claymore" ]
}, {
    name: "Mira",
    gender: "Female",
    role: "Support",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2017,
    primaryWeapons: [ "Vector .45 ACP", "ITA12S" ],
    secondaryWeapons: [ "LFP586" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Lesion",
    gender: "Male",
    role: "Trapper",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2017,
    primaryWeapons: [ "T-95 LSW", "SUPERNOVA" ],
    secondaryWeapons: [ "Q-929" ],
    secondaryGadgets: [ "Proximity Alarm", "Impact Grenade" ]
}, {
    name: "Ying",
    gender: "Female",
    role: "Crowd Control",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2017,
    primaryWeapons: [ "T-95 LSW", "SIX12" ],
    secondaryWeapons: [ "Q-929" ],
    secondaryGadgets: [ "Frag Grenade", "Hard Breach Charge" ]
}, {
    name: "Ela",
    gender: "Female",
    role: "Trapper",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2017,
    primaryWeapons: [ "Scorpion EVO 3 A1", "Super 90" ],
    secondaryWeapons: [ "RG15" ],
    secondaryGadgets: [ "Barbed Wire", "Nitro Cell" ]
}, {
    name: "Zofia",
    gender: "Female",
    role: "Front Line",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2017,
    primaryWeapons: [ "M762", "ARX200" ],
    secondaryWeapons: [ "RG15" ],
    secondaryGadgets: [ "Impact Grenade", "Breach Charge" ]
}, {
    name: "Dokkaebi",
    gender: "Female",
    role: "Intel",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2017,
    primaryWeapons: [ "Bizon", "SR-25" ],
    secondaryWeapons: [ "PMM" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Vigil",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Defense",
    speed: 3,
    armor: 1,
    releaseYear: 2017,
    primaryWeapons: [ "K1A", "9x19VSN" ],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Proximity Alarm", "Impact Grenade" ]
}, {
    name: "Lion",
    gender: "Male",
    role: "Intel",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2018,
    primaryWeapons: [ "V308", "417" ],
    secondaryWeapons: [ "LFP586" ],
    secondaryGadgets: [ "Smoke Grenade", "Claymore" ]
}, {
    name: "Finka",
    gender: "Female",
    role: "Support",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2018,
    primaryWeapons: [ "Spear .308", "6P41" ],
    secondaryWeapons: [ "GSH-18" ],
    secondaryGadgets: [ "Frag Grenade", "Breach Charge" ]
}, {
    name: "Alibi",
    gender: "Female",
    role: "Trapper",
    side: "Defense",
    speed: 3,
    armor: 1,
    releaseYear: 2018,
    primaryWeapons: [ "MX4 Storm", "ACS12" ],
    secondaryWeapons: [ "ITA12S" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Maestro",
    gender: "Male",
    role: "Intel",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2018,
    primaryWeapons: [ "ALDA 5.56", "ACS12" ],
    secondaryWeapons: [ "Bailiff 410" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Maverick",
    gender: "Male",
    role: "Breach",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2018,
    primaryWeapons: [ "AR-15.50", "M4" ],
    secondaryWeapons: [ "1911 TACOPS" ],
    secondaryGadgets: [ "Frag Grenade", "Claymore" ]
}, {
    name: "Clash",
    gender: "Female",
    role: "Crowd Control",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2018,
    primaryWeapons: [],
    secondaryWeapons: [ "SPSMG9" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Kaid",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2018,
    primaryWeapons: [ "TCSG12", "AUG A3" ],
    secondaryWeapons: [ "Bailiff 410" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Nomad",
    gender: "Female",
    role: "Crowd Control",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2018,
    primaryWeapons: [ "AK-74M", "ARX200" ],
    secondaryWeapons: [ "ITA12L" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Gridlock",
    gender: "Female",
    role: "Crowd Control",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2019,
    primaryWeapons: [ "F90", "M249" ],
    secondaryWeapons: [ "Bearing 9" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Mozzie",
    gender: "Male",
    role: "Intel",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2019,
    primaryWeapons: [ "Commando 9", "P10 RONI" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Nitro Cell", "Impact Grenade" ]
}, {
    name: "Nøkk",
    gender: "Female",
    role: "Intel",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2019,
    primaryWeapons: [ "FMG-9", "SIX12 SD" ],
    secondaryWeapons: [ "5.7 USG" ],
    secondaryGadgets: [ "Frag Grenade", "Hard Breach Charge" ]
}, {
    name: "Warden",
    gender: "Male",
    role: "Support",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2019,
    primaryWeapons: [ "M590A1", "MP5" ],
    secondaryWeapons: [ "ITA12S" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Amaru",
    gender: "Female",
    role: "Front Line",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2019,
    primaryWeapons: [ "G8A1", "Supernova" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Frag Grenade", "Breach Charge" ]
}, {
    name: "Goyo",
    gender: "Male",
    role: "Anti-Entry",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2019,
    primaryWeapons: [ "TCSG12", "Talon-5" ],
    secondaryWeapons: [ "ITA12S" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Kali",
    gender: "Female",
    role: "Breach",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2019,
    primaryWeapons: [ "CSRX 300" ],
    secondaryWeapons: [ "SPSMG9", "C75 Auto" ],
    secondaryGadgets: [ "Smoke Grenade", "Claymore" ]
}, {
    name: "Wamai",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2019,
    primaryWeapons: [ "SMG-11", "M12" ],
    secondaryWeapons: [ "GSH-18" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Iana",
    gender: "Female",
    role: "Intel",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2020,
    primaryWeapons: [ "ARX200", "SIX12 SD" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Frag Grenade", "Hard Breach Charge" ]
}, {
    name: "Oryx",
    gender: "Male",
    role: "Front Line",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2020,
    primaryWeapons: [ "Bizon", "ITA12S" ],
    secondaryWeapons: [ "PMM" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Ace",
    gender: "Male",
    role: "Breach",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2020,
    primaryWeapons: [ "AK-12", "M1014" ],
    secondaryWeapons: [ "Q-929" ],
    secondaryGadgets: [ "Frag Grenade", "Claymore" ]
}, {
    name: "Melusi",
    gender: "Female",
    role: "Crowd Control",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2020,
    primaryWeapons: [ "Vector .45 ACP", "SIX12" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Zero",
    gender: "Male",
    role: "Intel",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2020,
    primaryWeapons: [ "417", "AR33" ],
    secondaryWeapons: [ "5.7 USG" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Aruni",
    gender: "Female",
    role: "Anti-Entry",
    side: "Defense",
    speed: 1,
    armor: 3,
    releaseYear: 2020,
    primaryWeapons: [ "ARX200", "SASG-12" ],
    secondaryWeapons: [ "PMM" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Flores",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2021,
    primaryWeapons: [ "SR-25", "AR33" ],
    secondaryWeapons: [ "P9" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Thunderbird",
    gender: "Female",
    role: "Support",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2021,
    primaryWeapons: [ "SIX12 SD", "TCSG12" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Osa",
    gender: "Female",
    role: "Support",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2021,
    primaryWeapons: [ "556XI", "SIX12" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Thorn",
    gender: "Female",
    role: "Trapper",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2021,
    primaryWeapons: [ "614-Precision", "ITA12L" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Azami",
    gender: "Female",
    role: "Anti-Entry",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2022,
    primaryWeapons: [ "ISG", "Vector .45 ACP" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Sens",
    gender: "Non-binary",
    role: "Support",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2022,
    primaryWeapons: [ "417", "AR33" ],
    secondaryWeapons: [ "GSH-18" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Grim",
    gender: "Male",
    role: "Intel",
    side: "Attack",
    speed: 3,
    armor: 1,
    releaseYear: 2022,
    primaryWeapons: [ "SIX12", "ITA12L" ],
    secondaryWeapons: [ "5.7 USG" ],
    secondaryGadgets: [ "Smoke Grenade", "Hard Breach Charge" ]
}, {
    name: "Solis",
    gender: "Female",
    role: "Intel",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2022,
    primaryWeapons: [ "SR-25", "M590A1" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Brava",
    gender: "Female",
    role: "Anti-Gadget",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2023,
    primaryWeapons: [ "556XI", "M249" ],
    secondaryWeapons: [ "GSH-18" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Fenrir",
    gender: "Male",
    role: "Crowd Control",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2023,
    primaryWeapons: [ "MPX", "SASG-12" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Ram",
    gender: "Female",
    role: "Breach",
    side: "Attack",
    speed: 1,
    armor: 3,
    releaseYear: 2023,
    primaryWeapons: [ "ARX200", "556XI" ],
    secondaryWeapons: [ "GSH-18" ],
    secondaryGadgets: [ "Frag Grenade", "Claymore" ]
}, {
    name: "Tubarão",
    gender: "Male",
    role: "Anti-Gadget",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2023,
    primaryWeapons: [ "M870", "PARA-308" ],
    secondaryWeapons: [ "Bailiff 410" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Deimos",
    gender: "Male",
    role: "Intel",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2024,
    primaryWeapons: [ "556XI", "M249" ],
    secondaryWeapons: [ "P226 Mk 25" ],
    secondaryGadgets: [ "Frag Grenade", "Smoke Grenade" ]
}, {
    name: "Striker",
    gender: "Variable",
    role: "Support",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2024,
    playable: false,
    primaryWeapons: [],
    secondaryWeapons: [],
    secondaryGadgets: []
}, {
    name: "Sentry",
    gender: "Variable",
    role: "Support",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2024,
    playable: false,
    primaryWeapons: [],
    secondaryWeapons: [],
    secondaryGadgets: []
}, {
    name: "Skopós",
    gender: "Female",
    role: "Intel",
    side: "Defense",
    speed: 2,
    armor: 2,
    releaseYear: 2024,
    primaryWeapons: [ "417", "M1014" ],
    secondaryWeapons: [ "SDP 9mm" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
}, {
    name: "Rauora",
    gender: "Female",
    role: "Support",
    side: "Attack",
    speed: 2,
    armor: 2,
    releaseYear: 2025,
    primaryWeapons: [ "417", "M249" ],
    secondaryWeapons: [ "GSH-18", "Reaper MK2" ],
    secondaryGadgets: [ "Smoke Grenade", "Breach Charge" ]
}, {
    name: "Denari",
    gender: "Male",
    role: "Anti-Entry",
    side: "Defense",
    speed: 3,
    armor: 1,
    releaseYear: 2025,
    primaryWeapons: [ "M12", "AR33" ],
    secondaryWeapons: [ "P12" ],
    secondaryGadgets: [ "Barbed Wire", "Impact Grenade" ]
} ];

const OPERATORS = RAW_OPERATORS.map(op => ({
    ...op,
    image: `pngs/${slugifyOperatorName(op.name)}.png`,
    playable: op.playable !== undefined ? op.playable : true,
    primaryWeapons: op.primaryWeapons || [],
    secondaryWeapons: op.secondaryWeapons || [],
    secondaryGadgets: op.secondaryGadgets || []
}));

const PLAYABLE_OPERATORS = OPERATORS.filter(op => op.playable);
